CREATE TABLE IF NOT EXISTS inquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference_code VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  company VARCHAR(200) NOT NULL,
  email VARCHAR(254) NOT NULL,
  category VARCHAR(20) NOT NULL,
  message VARCHAR(4000) NOT NULL,
  consented BOOLEAN NOT NULL,
  ip_hash VARCHAR(64) NOT NULL,
  created_at TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_inquiries_email_created ON inquiries (email, created_at)
